version: '3.7'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --capture-output --log-level debug -k uvicorn.workers.UvicornWorker --access-logfile ./gunicorn-access.log app.main:app --bind 0.0.0.0:8000 --workers 4'
    volumes:
      - ./app:/code/app
      - ./uploads:/code/uploads
    ports:
      - 8000:8000
    environment:
      - SECRET=${SECRET}
      - ADMIN_KEY=${ADMIN_KEY}
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:15-alpine
    volumes:
      - main-db:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure

volumes:
  main-db:
